[workspace]
members = ["crates/engine", "crates/launcher"]
default-members = ["crates/engine", "crates/launcher"]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1

[workspace.package]
version = "2.2.1"
edition = "2021"
publish = false

[workspace.dependencies]
core-engine = { path = "crates/engine" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "43585afc29ea95e0c879309e08436bc25f5fab16" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "43585afc29ea95e0c879309e08436bc25f5fab16" }
