mod auto_save;
pub(crate) mod control_style;
mod document;
pub mod quicklink_table;
mod scrollbar;
pub use document::SettingsDocument;
mod display;
pub mod layout;
mod model;
mod music;
mod music_section;
pub mod page;
mod position_preview;
mod shortcut;
pub mod shortcut_recorder;
mod slider;
mod startup;
mod store;
mod window_metrics;

pub use auto_save::{AutoSave, AUTO_SAVE_TIMER};
pub use display::DisplayChoice;
pub use model::{BackgroundColor, Preferences, ScreenPosition};
pub use music::{MediaShortcutAction, MusicApp, MusicSettings, ShortcutScope};
pub use shortcut::Shortcut;
pub use store::{SettingsStore, SETTINGS_SAVED};
pub use window_metrics::{CornerRadius, EdgeSpacing};
