mod auto_save;
mod control_style;
mod document;
pub mod quicklink_table;
mod scrollbar;
pub use document::SettingsDocument;
mod display;
pub mod layout;
mod model;
pub mod page;
mod position_preview;
mod shortcut;
mod slider;
mod startup;
mod store;
mod window_metrics;

pub use auto_save::{AutoSave, AUTO_SAVE_TIMER};
pub use display::DisplayChoice;
pub use model::{BackgroundColor, Preferences, ScreenPosition};
pub use shortcut::Shortcut;
pub use store::{SettingsStore, SETTINGS_SAVED};
pub use window_metrics::{CornerRadius, EdgeSpacing};
